on: [push]

name: Build and deploy

jobs:
  build-app:
    name: Build Ionic App
    runs-on: ubuntu-latest
    steps:
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build App
        run: |
          cd komunat
          npm rebuild node-sass && npm install
          ionic build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: komunat/www
  deploy:
    name: DockerHub Deployment
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: komunat/pwa
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: komunat/Dockerfile
          tags: "2019"
